package entity;
// Generated Apr 4, 2018 6:53:33 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer BId;
     private String TName;
     private String TPhone;
     private String TDistance;
     private Date waitingTime;

    public Bill() {
    }

    public Bill(String TName, String TPhone, String TDistance, Date waitingTime) {
       this.TName = TName;
       this.TPhone = TPhone;
       this.TDistance = TDistance;
       this.waitingTime = waitingTime;
    }
   
    public Integer getBId() {
        return this.BId;
    }
    
    public void setBId(Integer BId) {
        this.BId = BId;
    }
    public String getTName() {
        return this.TName;
    }
    
    public void setTName(String TName) {
        this.TName = TName;
    }
    public String getTPhone() {
        return this.TPhone;
    }
    
    public void setTPhone(String TPhone) {
        this.TPhone = TPhone;
    }
    public String getTDistance() {
        return this.TDistance;
    }
    
    public void setTDistance(String TDistance) {
        this.TDistance = TDistance;
    }
    public Date getWaitingTime() {
        return this.waitingTime;
    }
    
    public void setWaitingTime(Date waitingTime) {
        this.waitingTime = waitingTime;
    }




}


