package entity;
// Generated Apr 4, 2018 6:53:33 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer BId;
     private String CCity;
     private String CCar;
     private String PLocation;
     private String DLocation;
     private Date PDate;

    public Book() {
    }

    public Book(String CCity, String CCar, String PLocation, String DLocation, Date PDate) {
       this.CCity = CCity;
       this.CCar = CCar;
       this.PLocation = PLocation;
       this.DLocation = DLocation;
       this.PDate = PDate;
    }
   
    public Integer getBId() {
        return this.BId;
    }
    
    public void setBId(Integer BId) {
        this.BId = BId;
    }
    public String getCCity() {
        return this.CCity;
    }
    
    public void setCCity(String CCity) {
        this.CCity = CCity;
    }
    public String getCCar() {
        return this.CCar;
    }
    
    public void setCCar(String CCar) {
        this.CCar = CCar;
    }
    public String getPLocation() {
        return this.PLocation;
    }
    
    public void setPLocation(String PLocation) {
        this.PLocation = PLocation;
    }
    public String getDLocation() {
        return this.DLocation;
    }
    
    public void setDLocation(String DLocation) {
        this.DLocation = DLocation;
    }
    public Date getPDate() {
        return this.PDate;
    }
    
    public void setPDate(Date PDate) {
        this.PDate = PDate;
    }




}


