package entity;
// Generated Apr 4, 2018 6:53:33 AM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer catId;
     private String chooseCity;
     private String maxBillCharge;
     private String freeKm;
     private String waitingCharge;
     private String extraCharge;

    public Category() {
    }

    public Category(String chooseCity, String maxBillCharge, String freeKm, String waitingCharge, String extraCharge) {
       this.chooseCity = chooseCity;
       this.maxBillCharge = maxBillCharge;
       this.freeKm = freeKm;
       this.waitingCharge = waitingCharge;
       this.extraCharge = extraCharge;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getChooseCity() {
        return this.chooseCity;
    }
    
    public void setChooseCity(String chooseCity) {
        this.chooseCity = chooseCity;
    }
    public String getMaxBillCharge() {
        return this.maxBillCharge;
    }
    
    public void setMaxBillCharge(String maxBillCharge) {
        this.maxBillCharge = maxBillCharge;
    }
    public String getFreeKm() {
        return this.freeKm;
    }
    
    public void setFreeKm(String freeKm) {
        this.freeKm = freeKm;
    }
    public String getWaitingCharge() {
        return this.waitingCharge;
    }
    
    public void setWaitingCharge(String waitingCharge) {
        this.waitingCharge = waitingCharge;
    }
    public String getExtraCharge() {
        return this.extraCharge;
    }
    
    public void setExtraCharge(String extraCharge) {
        this.extraCharge = extraCharge;
    }




}


