package entity;
// Generated Apr 4, 2018 6:53:33 AM by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer DId;
     private String DName;
     private String DPhone;
     private String DEmail;
     private String DAddress;
     private String DLisence;

    public Contact() {
    }

    public Contact(String DName, String DPhone, String DEmail, String DAddress, String DLisence) {
       this.DName = DName;
       this.DPhone = DPhone;
       this.DEmail = DEmail;
       this.DAddress = DAddress;
       this.DLisence = DLisence;
    }
   
    public Integer getDId() {
        return this.DId;
    }
    
    public void setDId(Integer DId) {
        this.DId = DId;
    }
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }
    public String getDPhone() {
        return this.DPhone;
    }
    
    public void setDPhone(String DPhone) {
        this.DPhone = DPhone;
    }
    public String getDEmail() {
        return this.DEmail;
    }
    
    public void setDEmail(String DEmail) {
        this.DEmail = DEmail;
    }
    public String getDAddress() {
        return this.DAddress;
    }
    
    public void setDAddress(String DAddress) {
        this.DAddress = DAddress;
    }
    public String getDLisence() {
        return this.DLisence;
    }
    
    public void setDLisence(String DLisence) {
        this.DLisence = DLisence;
    }




}


